[workspace]
resolver = "3"
members = ["crates/*", "napi/*"]

[workspace.package]
authors = ["Liang Mi <https://github.com/liangmiQwQ>", "contributors"]
categories = ["compilers", "development-tools", "web-programming"]
keywords = ["UMC", "parser", "HTML", "CSS", "JSON", "AST"]
license = "MIT"
repository = "https://github.com/liangmiQwQ/umc"
description = "The Universal Markup-language Compiler, Rust-based."

edition = "2024"
rust-version = "1.89.0"
